[package]
name = "ustc-agentd"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
axum.workspace = true
reqwest.workspace = true
ustc-campus-agent-runtime = { path = "../../crates/agent-runtime" }
ustc-agent-tool-protocol.workspace = true
ustc-campus-agent-core = { path = "../../crates/platform-core" }
ustc-campus-agent-application-ingress = { path = "../../crates/application-ingress" }
ustc-campus-agent-client-protocol = { path = "../../crates/client-protocol" }
affairs-navigator = { path = "../../crates/affairs-navigator" }
libc.workspace = true
ustc-campus-agent-change-radar = { path = "../../crates/change-radar" }
ustc-campus-agent-course-planning = { path = "../../crates/course-planning" }
ustc-campus-agent-opportunity-graph = { path = "../../crates/opportunity-graph" }
ustc-campus-agent-simple-calendar = { path = "../../crates/simple-calendar" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true

[lints]
workspace = true
