[package]
name = "ustc-agent-tool-protocol"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
sha2.workspace = true

[lints]
workspace = true
