[package]
name = "ustc-campus-agent-core"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
ustc-agent-tool-protocol.workspace = true

[dev-dependencies]
hex = "0.4.3"

[lib]
path = "src/lib.rs"

[lints]
workspace = true
